include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_specify_types
    - avoid_dynamic_calls
    - avoid_catching_errors
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - collection_methods_unrelated_type
    - combinators_ordering
    - constant_identifier_names
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - eol_at_end_of_file
    - exhaustive_cases
    - file_names
    - flutter_style_todos
    - implementation_imports
    - hash_and_equals
    - library_names
    - library_prefixes
    - lines_longer_than_80_chars
    - literal_only_boolean_expressions
    - no_duplicate_case_values
    - no_logic_in_create_state
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_if_null_operators
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - require_trailing_commas
    - sized_box_for_whitespace
    - sized_box_shrink_expand
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_pub_dependencies
    - super_goes_last
    - type_annotate_public_apis
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_breaks
    - unnecessary_const
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_parenthesis
    - unnecessary_string_interpolations
    - unnecessary_this
    - use_decorated_box
    - use_build_context_synchronously
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_string_in_part_of_directives
    - use_super_parameters

analyzer:
  exclude:
    - "lib/presentation/l10n/generated/**"

  errors:
    use_build_context_synchronously: ignore
    prefer_const_constructors: ignore
