name: base
description: "Flutter project base."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  auto_size_text: ^3.0.0
  awesome_snackbar_content: ^0.1.3
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  #flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.10+1
  go_router: ^16.2.0
  google_fonts: ^6.3.1
  iconsax: ^0.0.8
  intl: ^0.20.2
  responsive_framework: ^1.4.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: en
  class_name: L10n
  arb_dir: lib/presentation/l10n/l10n
  output_dir: lib/presentation/l10n/generated
